/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.appsflyer;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.TiProperties;

import com.appsflyer.AppsFlyerLib;

@Kroll.module(name = "Tiappsflyer", id = "ti.appsflyer")
public class TiappsflyerModule extends KrollModule {

	// Standard Debugging variables
	private TiProperties appProperties;
	private static final String LCAT = "AppsFlyer >>>>>";
	String appId;
	String appUserId;
	String devKey;
	AppsFlyerLib instance;
	TiApplication ctx = TiApplication.getInstance();

	public TiappsflyerModule() {
		super();
		this.instance = AppsFlyerLib.getInstance();
		Log.i(LCAT, "AppsFlyer module initiated");
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		Log.i(LCAT, "onAppCreate started");
	}

	// Methods
	// private void importProperties(String appId, String devKey) {
	// 	appProperties = TiApplication.getInstance().getAppProperties();
	// 	this.appId = appId;
	// 	this.devKey = devKey;

//	 	Log.i(LCAT, "AppsFlyer App Id: " + this.appId);
//	 	Log.i(LCAT, "AppsFlyer Dev Key: " + this.devKey);
//		
//	 	if (appId.equals(""))
//	 	{
//	 		Log.i(LCAT, "Don't forget appID");
//	 	}
//	 	if (devKey.equals(""))
//	 	{
//	 		Log.i(LCAT, "Don't forget devKey");
//	 	}
//	 }

	@SuppressWarnings("deprecation")
	@Kroll.method
	public void startTracker(String appId, String devKey) {
		// importProperties();
		Log.i(LCAT, "AppsFlyer start tracker");

		this.appId = appId;
		this.devKey = devKey;

		Log.i(LCAT, "AppsFlyer App Id: " + this.appId);
		Log.i(LCAT, "AppsFlyer Dev Key: " + this.devKey);
//		
		instance.setAppId(appId);
		
		// To initialize the SDK
		// your devKey is in your AppsFlyer account app settings
		instance.startTracking(ctx, devKey);
		
		Log.i(LCAT, "AppsFlyer SDK initialized");
		
	}

	@Kroll.method
	public void setCustomerUserId(String customerId) {
		instance.setCustomerUserId(customerId);
		Log.i(LCAT, "AppsFlyer Customer Id set: " + customerId);
	}

	@Kroll.method
	public void trackAppLaunch() {
		instance.trackAppLaunch(ctx, devKey);
		Log.i(LCAT, "AppsFlyer App Launch Tracked");
	}

	@Kroll.method
	public void trackAction(String eventName, KrollDict dict) {
		if (dict != null) {
			instance.trackEvent(ctx, eventName, dict);
			Log.i(LCAT, "AppsFlyer Event tracked: Event: " + eventName + "data: " + dict.toString());
		}
	}
}